import setuptools

setuptools.setup(
    name="pqc_expressibility_estimator",
    version="0.1.0",
    author="Timur Gubaev",
    author_email="timur.gubaev@tu-ilmenau.de",
    description=(
        "Expressibility estimator for parameterized quantum circuits."
    ),
    long_description=(
        "Expressibility estimator for parameterized quantum circuits. Measures circuit expressibility via the KL divergence between the fidelity distribution of Haar-random states and that generated by the circuit. Requires Qiskit and Qiskit Aer."
    ),
    long_description_content_type="text/markdown",
    url="https://github.com/tgubaev/pqc-expressibility-estimator",
    packages=setuptools.find_packages(),
    python_requires='>=3.6',
    install_requires=[
        'numpy',
        'qiskit',
        'qiskit-aer'
    ],
)
